apiVersion: v1
kind: Namespace
metadata:
  name: fibonacci-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
  namespace: fibonacci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
      - name: us
        image: siyingchen/us:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: us-service
  namespace: fibonacci-app
spec:
  selector:
    app: us
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
  namespace: fibonacci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
      - name: fs
        image: siyingchen/fs:latest
        ports:
        - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: fs-service
  namespace: fibonacci-app
spec:
  selector:
    app: fs
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
  namespace: fibonacci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: as
        image: siyingchen/as:latest
        ports:
        - containerPort: 53533

---

apiVersion: v1
kind: Service
metadata:
  name: as-service
  namespace: fibonacci-app
spec:
  selector:
    app: as
  type: NodePort
  ports:
  - protocol: UDP
    port: 53533
    targetPort: 53533
    nodePort: 30001

