version: '3'
services:
  us-service1:
    image: siyingchen/us:latest  
    ports:
      - "30003:8080" 
    networks:
      - fibonacci-network

  fs-service:
    image: siyingchen/fs:latest  
    ports:
      - "30002:9090" 
    networks:
      - fibonacci-network

  as-service:
    image: siyingchen/as:latest  
    ports:
      - "30001:53533/udp" 
    networks:
      - fibonacci-network

networks:
  fibonacci-network:
    driver: bridge
